# Generated by Django 5.2.11 on 2026-03-16 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_received', 'New booking received'), ('booking_accepted', 'Booking accepted'), ('booking_rejected', 'Booking rejected'), ('booking_cancelled', 'Booking cancelled'), ('booking_refunded', 'Refund initiated'), ('review_received', 'New review on your property'), ('complaint_update', 'Complaint status updated'), ('message_received', 'New message'), ('listing_approved', 'Listing approved'), ('listing_rejected', 'Listing rejected')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
