# Generated by Django 5.2.11 on 2026-02-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_sellerphoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pan_verified',
            field=models.BooleanField(default=False),
        ),
    ]
