# Generated by Django 5.2.11 on 2026-02-07 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_seller_pan_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='properties',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='properties',
            name='availability_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='properties',
            name='bhk',
            field=models.CharField(choices=[('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk+', '4+ BHK / More')], default='1bhk', max_length=10),
        ),
        migrations.AddField(
            model_name='properties',
            name='built_up_area',
            field=models.DecimalField(decimal_places=2, default=2, help_text='in sq. ft.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='city',
            field=models.CharField(default='Kozhikode', max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='conditions_pdf',
            field=models.FileField(blank=True, help_text='Upload terms & conditions PDF', null=True, upload_to='conditions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='properties',
            name='furnishing',
            field=models.CharField(choices=[('full', 'Fully Furnished'), ('semi', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20),
        ),
        migrations.AddField(
            model_name='properties',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('studio', 'Studio'), ('commercial', 'Commercial')], default='apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='properties',
            name='purpose',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='sale', max_length=10),
        ),
    ]
