# Generated by Django 5.2.11 on 2026-02-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_properties_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleremailotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
