# Generated by Django 5.2.11 on 2026-02-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_selleremailotp_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('flat', 'Flat')], default='apartment', max_length=20),
        ),
    ]
