# Generated by Django 5.2.11 on 2026-03-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('complaint_type', models.CharField(choices=[('incorrect_listing', 'Incorrect listing details'), ('fraudulent_property', 'Fraudulent property'), ('agent_misconduct', 'Agent misconduct'), ('payment_issue', 'Payment issue'), ('technical_bug', 'Technical / app bug'), ('other', 'Other')], default='other', max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
