# Generated by Django 5.2.11 on 2026-03-25 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='admin_rejection_note',
            field=models.TextField(blank=True, help_text='Optional note from admin when rejecting a listing', null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='legal_document',
            field=models.FileField(blank=True, help_text='Upload supporting legal document (tax receipt, ownership proof, etc.)', null=True, upload_to='legal_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='properties',
            name='listing_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin must approve before listing is visible', max_length=10),
        ),
    ]
