# Generated by Django 6.0.1 on 2026-04-12 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_properties_admin_rejection_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReceiptVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='tax_receipts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('extracting', 'Extracting Data'), ('extracted', 'Data Extracted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('failed', 'Extraction Failed')], default='pending', help_text='Current verification status', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Data extracted from tax receipt (property details, tax amount, etc.)')),
                ('is_manually_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Admin notes on verification')),
                ('extraction_error', models.TextField(blank=True, help_text='Error message if extraction failed')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_verification', to='app1.properties')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_taxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
