# Generated by Django 6.0.1 on 2026-04-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_taxreceiptverification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='properties',
            index=models.Index(fields=['listing_status', '-created_at'], name='app1_proper_listing_ed482d_idx'),
        ),
        migrations.AddIndex(
            model_name='properties',
            index=models.Index(fields=['seller', 'listing_status'], name='app1_proper_seller__271255_idx'),
        ),
        migrations.AddIndex(
            model_name='properties',
            index=models.Index(fields=['city', 'property_type', 'listing_status'], name='app1_proper_city_f38151_idx'),
        ),
        migrations.AddIndex(
            model_name='properties',
            index=models.Index(fields=['created_at'], name='app1_proper_created_22fa17_idx'),
        ),
        migrations.AddIndex(
            model_name='properties',
            index=models.Index(fields=['price'], name='app1_proper_price_db7f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'order'], name='app1_proper_propert_1dd8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['uploaded_at'], name='app1_proper_uploade_2e8df5_idx'),
        ),
    ]
