# Generated by Django 6.0.1 on 2026-04-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_properties_app1_proper_listing_ed482d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxreceiptverification',
            name='verification_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Structured verification details such as portal checks, fraud flags, and score'),
        ),
        migrations.AddField(
            model_name='taxreceiptverification',
            name='verification_source',
            field=models.CharField(default='automatic', help_text='Source of the verification result, such as automatic or manual', max_length=30),
        ),
    ]
