# Generated by Django 5.2.11 on 2026-02-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seller_amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='property_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=12),
            preserve_default=False,
        ),
    ]
